### ISSUE TITLE
Sitemap should be optional?

### ISSUE THREAD

**Issue by afrubin** [dms-viz/configure_dms_viz#20]
It seems like the sitemap should be optional for datasets where the sites given in the input file satisfy the requirements for the sequential site. It's clear that the sitemap file is important for many datasets, but it's odd to require one since probably the majority of non-viral datasets won't need it and it just creates extra work for the user.

This issue is part of https://github.com/openjournals/joss-reviews/issues/6129

**Comment by WillHannon-MCB** [comment]
Good point. I've made the `sitemap` an option. If you do not provide one, all sites are sequential and the reference sites in your input data are the same as the protein sites.
