### ISSUE TITLE
Test granularity

### ISSUE THREAD

**Issue by afrubin** [dms-viz/configure_dms_viz#21]
I tried running the tests and while they did pass after a few minutes, I was surprised that pytest reported running exactly one test.

Looking at the test files, it appears that this one test is a consistency test for all of the example files. There doesn't appear to be any sort of unit tests or other more granular tests to ensure correctness of the processing. This would also make it very challenging for other developers to contribute to this code.

I think there needs to be some level of function-based testing, including making sure that expected exceptions are caught. A much smaller example dataset (i.e. not a full real dataset) that's used for testing could also be instructive for users.

This issue is part of https://github.com/openjournals/joss-reviews/issues/6129

**Comment by WillHannon-MCB** [comment]
I added more unit tests for individual functions. I kept the test of the command line utility as well. I like that test because it generates the example datasets used in the documentation.
