### ISSUE TITLE
Warning messages about structure agreement

### ISSUE THREAD

**Issue by afrubin** [dms-viz/configure_dms_viz#22]
The dataset I tried formatted correctly on the first try, which was very exciting! I did get the following warning message:

```
About 76.82% of the wildtype residues in the data match the corresponding residues in the structure.
About 23.18% of the data sites are missing from the structure.
```

It seems like the wildtype residues that don't match are very likely to be the missing ones. I think it would be more informative to make two changes:
* Don't count "missing in the structure" as a lack of agreement, since this implies that there's a mismatch between my experimental wildtype sequence and the structure sequence rather than no data.
* Give numbers in parentheses in addition to the percentages. For example, it would have been nicer to see `About 76.82% (123 of 456) of the wildtype residues...`

This issue is part of https://github.com/openjournals/joss-reviews/issues/6129

**Comment by WillHannon-MCB** [comment]
Fixed!
