### ISSUE TITLE
Filters need more documentation

### ISSUE THREAD

**Issue by afrubin** [dms-viz/configure_dms_viz#23]
Right now the description of how to add filters and tooltips in the documentation is pretty bare-bones, and users would need to refer to a specific example dataset to try to figure out how to do it. It would be good to see a fully worked example of preparing additional contextual files with `format` and then using `join` to put it together, including a description of what the extra data columns are.

This should be distinct from another example showing how to combine and visualize multiple datasets.

This issue is part of https://github.com/openjournals/joss-reviews/issues/6129

**Comment by WillHannon-MCB** [comment]
I added [additional information](https://dms-viz.github.io/dms-viz-docs/preparing-data/command-line-api/#advanced-usage) to the documentation and pointed to specific examples.
