### ISSUE TITLE
Allow for non-symmetric limits in the color scales

### ISSUE THREAD

**Issue by jbloom** [dms-viz/configure_dms_viz#33]
Are these symmetric around the min and max of the displayed site metric?

If so, would there be a way to set limits on them potentially when non-symmetric limits make more sense?

**Comment by WillHannon-MCB** [comment]
The limits are symmetric around the absolute max of the site metric. I'm working on an update so you can set non-symmetric limits and set the [center of the scale](https://github.com/dms-viz/dms-viz.github.io/issues/85).
