### ISSUE TITLE
bug w `configure-dms-viz` join

### ISSUE THREAD

**Issue by jbloom** [dms-viz/configure_dms_viz#34]
I have attached JSONs for three different phenotypes (a26_usage, stability, cell entry) as well as a joined JSON created with:

     configure-dms-viz join --input cell_entry.json stability.json a26_usage.json --output dms-viz.json

The joined JSON is wrong. The y-axis title for the phenotypes of all datasets in the joined dataset always has the title for cell entry, and is a problem with the tooltips as well as the cell entry phenotype is shown as the value for other main phenotypes for other datasets.

[a26_usage.json](https://github.com/dms-viz/configure_dms_viz/files/15324601/a26_usage.json)
[cell_entry.json](https://github.com/dms-viz/configure_dms_viz/files/15324603/cell_entry.json)
[dms-viz.json](https://github.com/dms-viz/configure_dms_viz/files/15324605/dms-viz.json)
[stability.json](https://github.com/dms-viz/configure_dms_viz/files/15324606/stability.json)

**Comment by WillHannon-MCB** [comment]
Huh, that's strange. I'll see what's going on and fix it.

**Comment by WillHannon-MCB** [comment]
Fixed by [this pull request](https://github.com/dms-viz/dms-viz.github.io/pull/87).
