### ISSUE TITLE
question re the `--join-data` command

### ISSUE THREAD

**Issue by jbloom** [dms-viz/configure_dms_viz#37]
@WillHannon-MCB Is there any savings in file size of the JSON created by `configure-dms-viz` by using `--join-data` rather than just putting the column of interest in `--input`?

In other words, if `--input` has many conditions and I am joining the same site-mutation data to `--input` for each condition, does it make the resulting JSON any smaller if I use `--join-data` rather than `--input`? I'm just trying to figure out if there is any reason for me not to do the joining myself on the inputs upstream of `configure-dms-viz`?

**Comment by WillHannon-MCB** [comment]
There isn't effectively a difference. I added this as a convenience for people quickly putting together visualizations. It's a perfectly reasonable approach to join data upstream If you're integrating `configure-dms-viz` into a pipeline.
