### ISSUE TITLE
sort the JSON consistently for diffing?

### ISSUE THREAD

**Issue by jbloom** [dms-viz/configure_dms_viz#39]
@WillHannon-MCB, as best I can tell, running the command multiple times on the exact same dataset and commands can give different output because (I think) the keys in some parts of the JSON are not consistently sorted. (Let me know if this is incorrect and I am instead doing something wrong.)

Assuming this is the case, can you make the JSON consistently sorted?

This would just greatly help for pipelines where it would mean you would not keep getting `git diffs`'s from running the exact same thing.

**Comment by WillHannon-MCB** [comment]
@jbloom, can you provide an example? A diff or two files that `git` thinks are different? A link to a commit where this happened will also work. It could be the dictionary keys or something in the dictionary.
