### ISSUE TITLE
download session

### ISSUE THREAD

**Issue by Bernadetadad** [dms-viz/configure_dms_viz#4]
Is it possible to be able to export not only png but also the whole view session, or maybe get a unique url to it or something?

**Comment by Bernadetadad** [comment]
What do you mean by remote source? I've uploaded my json file but the URL is still 'https://dms-viz.github.io'
<img width="599" alt="image" src="https://github.com/dms-viz/configure_dms_viz/assets/22810662/169cdbba-03c4-4e05-8886-62615b055332">

**Comment by Bernadetadad** [comment]
ok you mean this ?
<img width="242" alt="image" src="https://github.com/dms-viz/configure_dms_viz/assets/22810662/c9fefc1b-4f39-4e4f-970b-f72373cfc5c4">

But that means you have to have your json on github or something, right?

**Comment by WillHannon-MCB** [comment]
Yes, that's the place! The easiest thing to do is to upload your JSON to GitHub. 

If you don't want to put that data in a repo, you can you something called a [Gist](https://gist.github.com/). It's like a mini repo that can host a single file. [Here's](https://gist.github.com/WillHannon-MCB/20d4d4ab3290d467913634171e10df34) and example. You can click on the `raw` button next to the file and copy that URL and paste it into the tool.

**Comment by Bernadetadad** [comment]
ok, I'll probably just make a structure folder in relevant DMS repos to store these. Thanks
